import * as THREE from 'three'
import { SPAWN_HALF } from '../constants'
import type { MapId } from '../constants'
import os_arena from '../maps/os_arena/raw.json'
import os_india from '../maps/os_india/raw.json'
import os_pillars from '../maps/os_pillars/raw.json'
import os_pool_day from '../maps/os_pool_day/raw.json'
import os_test from '../maps/os_test/raw.json'
import { parseGeo, isEmptyCompiled } from './mapGeometryCache'
import type { CompiledMap } from './mapGeometryCache'

/**
 * Maps as data — the single source for the 3D arena (Arena), spawns (Match) and the top-down preview (MapPreview).
 * A block = a box: always yields a visible mesh + a Rapier collider (half-extents = size). `blocksBeam` (default
 * true) — whether the beam raycast hits it: cover/columns block the line of fire (true), perimeter
 * walls are decor+collider and the beam passes through (false), as in the original arena. The floor is drawn by Arena separately.
 *
 * Spawns are two eye-level anchor points facing each other along ±Z; the mode's spawn rule
 * (src/game/spawns.ts) maps seats onto them (1v1 — one each; 2v2 — team clusters; FFA — generated).
 * Jump height ≈ JUMP_FORCE²/(2·|GRAVITY|) ≈ 1.45 — platforms aren't taller, so they're reachable by jump.
 */

export type Vec3 = [number, number, number]

export interface MapBlock {
  pos: Vec3            // center (world coordinates)
  size: Vec3          // half-extents (like CuboidCollider)
  color: string
  blocksBeam?: boolean   // default true; false → noRaycast mesh (beam passes through, but a collider exists)
  rot?: Vec3           // Euler rotation (radians), e.g. ramp tilt around X; none by default
  shape?: 'box' | 'wedge'   // default box; wedge — a wedge ramp (triangular prism)
  dir?: number         // wedge side 0=+Z,1=+X,2=−Z,3=−X (rotation around Y)
  flip?: boolean       // wedge flipped along Y (slope underneath — an overhang)
  side?: boolean       // wedge laid on its side — vertical diagonal wall; ignores flip
  transparent?: boolean   // default false → opaque; true → semi-transparent
  passable?: boolean      // default false → has a collider; true → no collider (passable through)
  perimeter?: boolean     // editor-round-trip marker for a perimeter wall; the game ignores it
}

export interface GameMap {
  id: MapId            // also the UI label (there's no separate name)
  half: [number, number]   // arena floor half-extents [X, Z] — a map can be rectangular (longer along Z)
  floorColor: string
  blocks: MapBlock[]
  spawns: [Vec3, Vec3]   // the two anchor points (see the header comment)
  showBlockGrid?: boolean   // draw the cube grid in-game (default/absent — don't draw)
}

const WALL_H = 1.5       // perimeter wall half-height
const WALL_T = 0.25      // wall half-thickness

/** Four perimeter walls sized to the floor [hx, hz] (decor+collider, beam passes through). */
export function perimeter(color: string, hx: number, hz: number): MapBlock[] {
  const bb = false
  return [
    { pos: [0, WALL_H, -hz], size: [hx, WALL_H, WALL_T], color, blocksBeam: bb, perimeter: true },
    { pos: [0, WALL_H, hz], size: [hx, WALL_H, WALL_T], color, blocksBeam: bb, perimeter: true },
    { pos: [-hx, WALL_H, 0], size: [WALL_T, WALL_H, hz], color, blocksBeam: bb, perimeter: true },
    { pos: [hx, WALL_H, 0], size: [WALL_T, WALL_H, hz], color, blocksBeam: bb, perimeter: true },
  ]
}

// Maps are built in the embedded editor (#editor) and stored as data in src/maps/*.json (GameMap shape).
export const MAPS: Record<MapId, GameMap> = {
  os_arena: os_arena as unknown as GameMap,
  os_india: os_india as unknown as GameMap,
  os_pillars: os_pillars as unknown as GameMap,
  os_pool_day: os_pool_day as unknown as GameMap,
  os_test: os_test as unknown as GameMap,
}

export const MAP_IDS: MapId[] = ['os_arena', 'os_india', 'os_pillars', 'os_pool_day', 'os_test']

// Map artifacts (optional — generated by the editor on save; bundled by Vite, work in prod).
// id is extracted from the path '../maps/<id>/<file>'.
const idOf = (p: string): MapId => p.split('/').slice(-2, -1)[0] as MapId

// Lazy geo.json loaders — Rolldown splits each file into its own chunk, loaded at match start.
const GEO_LOADERS = import.meta.glob('../maps/*/geo.json') as Record<string, () => Promise<{ default: unknown }>>
const _geoCache: Partial<Record<MapId, CompiledMap>> = {}

/** Start loading geo.json for map id (no-op if already cached). Call before mounting Arena. */
export async function ensureMapGeo(id: MapId): Promise<void> {
  if (id in _geoCache) return
  const path = Object.keys(GEO_LOADERS).find(p => idOf(p) === id)
  if (!path) return
  const mod = await GEO_LOADERS[path]()
  _geoCache[id] = parseGeo(mod.default as never)
}

/** Synchronously return the compiled map from cache (if preloaded via ensureMapGeo). Empty/outdated geo is treated
 * as missing → the consumer compiles from map.blocks (fallback), so the map doesn't break without a fresh geo.json. */
export function getCachedMapGeo(id: MapId): CompiledMap | undefined {
  const c = _geoCache[id]
  return c && !isEmptyCompiled(c) ? c : undefined
}

/** Preview image URL by id (preview.png). No file → undefined → live preview canvas (fallback). */
export const MAP_PREVIEW: Partial<Record<MapId, string>> = Object.fromEntries(
  Object.entries(import.meta.glob('../maps/*/preview.png', { eager: true, query: '?url', import: 'default' }) as Record<string, string>)
    .map(([p, url]) => [idOf(p), url]),
) as Partial<Record<MapId, string>>

// Keep references to warmed Images until loading completes — guarantees the request won't be canceled.
const warmedPreviews: HTMLImageElement[] = []

/** Warm up map previews: kick off image loading early (at app start) so room tiles
 *  and the background don't wait on the network on first entry — the browser caches them in the HTTP cache. Especially
 *  important for a #CODE client: they land in the room immediately while the network is busy with the bundle/sound/signaling. */
export function warmMapPreviews(): void {
  if (warmedPreviews.length) return   // once per session
  for (const url of Object.values(MAP_PREVIEW)) {
    if (!url) continue
    const img = new Image()
    img.src = url
    warmedPreviews.push(img)
  }
}

/** Random point within the play area — bot wandering (ignores obstacles; KCC prevents passing through). */
export function randomArenaPos(): THREE.Vector3 {
  return new THREE.Vector3(
    (Math.random() - 0.5) * SPAWN_HALF * 2,
    1,
    (Math.random() - 0.5) * SPAWN_HALF * 2,
  )
}
